services:
  - type: web
    name: roommorph
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3003
    autoDeploy: true
