services:
  - type: web
    name: roommorph
    env: node
    plan: free
    # NOTE: The buildCommand below is also likely to fail. 
    # See the important notes in the 'Secondary Issues' section.
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      npm install
      pip3 install pillow numpy transformers torch
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000 # ⬅️ CRITICAL FIX: Must match the default in server.js
    autoDeploy: true
    healthCheckPath: /health # ⬅️ Recommended: Add the health check path