services:
  - type: web
    name: roommorph
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      npm install
      pip3 install pillow numpy transformers torch
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3003
    autoDeploy: true
